language: node_js
node_js:
  - "12"
install:
  - yarn
script:
  - npm install
  - npm test
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: qYpf2cgBBG7Xx87MGsbFSXokrEOu27JnQsC2BoBTVWtMVKkdjzsMtNB1r5N7zKHB/N7TmJL8tELfPBA/ticCglT9QXkDwoUkOfX4N5WWGGwGNbfr2AG0Q7LE5pDVrbcWRk7yN1fFE7fum4WQ2GXj8UroaUU4Zwd8TsCC1p8oDEc0jy+rICVPXON1FZuKoqd/8xseoWqTwJtGju6ukARBYiuYX3tNtkOqcOSuXQrdEsvrkV1JhLRMPu8R9WKAeE9lN/DczCD/6KbQxyhBy0OT6kN92iMT6azV+jScH+vC1U93WbynFT1j4OGcDqarRZishJn1fjEGXaSrdhq/VirA6JSzdqqPv1RYsGU3yTY0zbfNkSzDJ84C/IVNdJS2lqN+dL5HSfrVFuROCO62e6juMbm5AJ1EvpVQqM5+3JN7Q4FQuMCaSsj1CfN12sZeS3iMuz3jP5T5WIRN5821Un2kvlX6+E9xCuGqjjgkH57taCIREVFbqm9XvlsFhHd9+/ZNBoS28gq0xxCHSkp5ALGkXl6vsoWg+ZVYynJSkQrROQwveHEFYi7oWqfDSnnR7dgKh8vpWrfcsR5ERLG9gBt5s3GmVk6TBtYk+3MBayjQ//xXPW3z8MoOKjc78JegITZ4Q8ybIoSOSEEF1T8Hshq4jODbpaTTTK3xRGjzzNFqE5c=
cache:
  directories:
    - node_modules